// ==============================================================
// Generated by Vitis HLS v2024.1.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="decode_can_message_decode_can_message,hls_ip_2024_1_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=11.099240,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=74015,HLS_SYN_LUT=112116,HLS_VERSION=2024_1_2}" *)

module decode_can_message (
        ap_clk,
        ap_rst_n,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        decoded_signals_address0,
        decoded_signals_ce0,
        decoded_signals_we0,
        decoded_signals_d0,
        hash_table_message_id_address0,
        hash_table_message_id_ce0,
        hash_table_message_id_q0,
        hash_table_lut_index_address0,
        hash_table_lut_index_ce0,
        hash_table_lut_index_q0,
        hash_table_accumulator_accumulated_values_address0,
        hash_table_accumulator_accumulated_values_ce0,
        hash_table_accumulator_accumulated_values_we0,
        hash_table_accumulator_accumulated_values_d0,
        hash_table_accumulator_accumulated_values_q0,
        hash_table_accumulator_accumulated_values_address1,
        hash_table_accumulator_accumulated_values_ce1,
        hash_table_accumulator_accumulated_values_we1,
        hash_table_accumulator_accumulated_values_d1,
        hash_table_accumulator_accumulated_values_q1,
        hash_table_accumulator_counter_address0,
        hash_table_accumulator_counter_ce0,
        hash_table_accumulator_counter_we0,
        hash_table_accumulator_counter_d0,
        hash_table_accumulator_counter_q0,
        msg_lut_address0,
        msg_lut_ce0,
        msg_lut_q0,
        signal_def_mem_address0,
        signal_def_mem_ce0,
        signal_def_mem_q0,
        signal_def_mem_address1,
        signal_def_mem_ce1,
        signal_def_mem_q1,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP
);

parameter    ap_ST_fsm_state1 = 12'd1;
parameter    ap_ST_fsm_state2 = 12'd2;
parameter    ap_ST_fsm_state3 = 12'd4;
parameter    ap_ST_fsm_state4 = 12'd8;
parameter    ap_ST_fsm_state5 = 12'd16;
parameter    ap_ST_fsm_state6 = 12'd32;
parameter    ap_ST_fsm_state7 = 12'd64;
parameter    ap_ST_fsm_state8 = 12'd128;
parameter    ap_ST_fsm_state9 = 12'd256;
parameter    ap_ST_fsm_state10 = 12'd512;
parameter    ap_ST_fsm_state11 = 12'd1024;
parameter    ap_ST_fsm_state12 = 12'd2048;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [6:0] decoded_signals_address0;
output   decoded_signals_ce0;
output   decoded_signals_we0;
output  [42:0] decoded_signals_d0;
output  [8:0] hash_table_message_id_address0;
output   hash_table_message_id_ce0;
input  [28:0] hash_table_message_id_q0;
output  [8:0] hash_table_lut_index_address0;
output   hash_table_lut_index_ce0;
input  [31:0] hash_table_lut_index_q0;
output  [15:0] hash_table_accumulator_accumulated_values_address0;
output   hash_table_accumulator_accumulated_values_ce0;
output   hash_table_accumulator_accumulated_values_we0;
output  [63:0] hash_table_accumulator_accumulated_values_d0;
input  [63:0] hash_table_accumulator_accumulated_values_q0;
output  [15:0] hash_table_accumulator_accumulated_values_address1;
output   hash_table_accumulator_accumulated_values_ce1;
output   hash_table_accumulator_accumulated_values_we1;
output  [63:0] hash_table_accumulator_accumulated_values_d1;
input  [63:0] hash_table_accumulator_accumulated_values_q1;
output  [8:0] hash_table_accumulator_counter_address0;
output   hash_table_accumulator_counter_ce0;
output   hash_table_accumulator_counter_we0;
output  [31:0] hash_table_accumulator_counter_d0;
input  [31:0] hash_table_accumulator_counter_q0;
output  [8:0] msg_lut_address0;
output   msg_lut_ce0;
input  [55:0] msg_lut_q0;
output  [8:0] signal_def_mem_address0;
output   signal_def_mem_ce0;
input  [79:0] signal_def_mem_q0;
output  [8:0] signal_def_mem_address1;
output   signal_def_mem_ce1;
input  [79:0] signal_def_mem_q1;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[15:0] hash_table_accumulator_accumulated_values_address0;
reg hash_table_accumulator_accumulated_values_ce0;
reg hash_table_accumulator_accumulated_values_we0;
reg[63:0] hash_table_accumulator_accumulated_values_d0;
reg[15:0] hash_table_accumulator_accumulated_values_address1;
reg hash_table_accumulator_accumulated_values_ce1;
reg hash_table_accumulator_accumulated_values_we1;
reg[8:0] signal_def_mem_address0;
reg signal_def_mem_ce0;
reg signal_def_mem_ce1;

 reg    ap_rst_n_inv;
(* fsm_encoding = "none" *) reg   [11:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [127:0] message;
wire   [31:0] num_decoded_signals_i;
reg   [31:0] num_decoded_signals_o;
reg    num_decoded_signals_o_ap_vld;
reg   [6:0] reg_255;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state11;
wire   [28:0] message_id_fu_262_p1;
reg   [28:0] message_id_reg_445;
wire   [8:0] hash_index_fu_283_p2;
reg   [8:0] hash_index_reg_450;
reg   [63:0] message_data_reg_455;
wire   [0:0] icmp_ln84_loc_load_load_fu_306_p1;
reg   [0:0] icmp_ln84_loc_load_reg_463;
wire    ap_CS_fsm_state3;
reg   [8:0] hash_table_accumulator_counter_addr_reg_472;
wire    ap_CS_fsm_state4;
wire   [8:0] trunc_ln117_fu_332_p1;
reg   [8:0] trunc_ln117_reg_489;
wire   [9:0] add_ln172_fu_345_p2;
reg   [9:0] add_ln172_reg_500;
wire    ap_CS_fsm_state8;
wire   [63:0] zext_ln172_fu_351_p1;
reg   [63:0] zext_ln172_reg_505;
reg   [8:0] hash_table_accumulator_counter_addr_1_reg_510;
wire   [15:0] add_ln184_fu_380_p2;
reg   [15:0] add_ln184_reg_515;
wire    ap_CS_fsm_state9;
reg   [31:0] hash_table_accumulator_counter_load_1_reg_520;
wire   [0:0] icmp_ln174_fu_386_p2;
reg   [0:0] icmp_ln174_reg_525;
wire    ap_CS_fsm_state10;
wire   [8:0] trunc_ln182_fu_397_p1;
reg   [8:0] trunc_ln182_reg_539;
reg   [31:0] num_decoded_signals_read_reg_544;
wire   [6:0] empty_fu_402_p1;
reg   [6:0] empty_reg_549;
wire    grp_decode_can_message_Pipeline_VITIS_LOOP_84_1_fu_205_ap_start;
wire    grp_decode_can_message_Pipeline_VITIS_LOOP_84_1_fu_205_ap_done;
wire    grp_decode_can_message_Pipeline_VITIS_LOOP_84_1_fu_205_ap_idle;
wire    grp_decode_can_message_Pipeline_VITIS_LOOP_84_1_fu_205_ap_ready;
wire   [8:0] grp_decode_can_message_Pipeline_VITIS_LOOP_84_1_fu_205_hash_table_message_id_address0;
wire    grp_decode_can_message_Pipeline_VITIS_LOOP_84_1_fu_205_hash_table_message_id_ce0;
wire   [8:0] grp_decode_can_message_Pipeline_VITIS_LOOP_84_1_fu_205_hash_index_1_out;
wire    grp_decode_can_message_Pipeline_VITIS_LOOP_84_1_fu_205_hash_index_1_out_ap_vld;
wire   [15:0] grp_decode_can_message_Pipeline_VITIS_LOOP_84_1_fu_205_mul_ln164_out;
wire    grp_decode_can_message_Pipeline_VITIS_LOOP_84_1_fu_205_mul_ln164_out_ap_vld;
wire   [0:0] grp_decode_can_message_Pipeline_VITIS_LOOP_84_1_fu_205_icmp_ln84_out;
wire    grp_decode_can_message_Pipeline_VITIS_LOOP_84_1_fu_205_icmp_ln84_out_ap_vld;
wire    grp_decode_can_message_Pipeline_VITIS_LOOP_117_2_fu_216_ap_start;
wire    grp_decode_can_message_Pipeline_VITIS_LOOP_117_2_fu_216_ap_done;
wire    grp_decode_can_message_Pipeline_VITIS_LOOP_117_2_fu_216_ap_idle;
wire    grp_decode_can_message_Pipeline_VITIS_LOOP_117_2_fu_216_ap_ready;
wire   [8:0] grp_decode_can_message_Pipeline_VITIS_LOOP_117_2_fu_216_signal_def_mem_address0;
wire    grp_decode_can_message_Pipeline_VITIS_LOOP_117_2_fu_216_signal_def_mem_ce0;
wire   [8:0] grp_decode_can_message_Pipeline_VITIS_LOOP_117_2_fu_216_signal_def_mem_address1;
wire    grp_decode_can_message_Pipeline_VITIS_LOOP_117_2_fu_216_signal_def_mem_ce1;
wire   [15:0] grp_decode_can_message_Pipeline_VITIS_LOOP_117_2_fu_216_hash_table_accumulator_accumulated_values_address0;
wire    grp_decode_can_message_Pipeline_VITIS_LOOP_117_2_fu_216_hash_table_accumulator_accumulated_values_ce0;
wire    grp_decode_can_message_Pipeline_VITIS_LOOP_117_2_fu_216_hash_table_accumulator_accumulated_values_we0;
wire   [63:0] grp_decode_can_message_Pipeline_VITIS_LOOP_117_2_fu_216_hash_table_accumulator_accumulated_values_d0;
wire   [15:0] grp_decode_can_message_Pipeline_VITIS_LOOP_117_2_fu_216_hash_table_accumulator_accumulated_values_address1;
wire    grp_decode_can_message_Pipeline_VITIS_LOOP_117_2_fu_216_hash_table_accumulator_accumulated_values_ce1;
wire    grp_decode_can_message_Pipeline_VITIS_LOOP_117_2_fu_216_hash_table_accumulator_accumulated_values_we1;
wire   [63:0] grp_decode_can_message_Pipeline_VITIS_LOOP_117_2_fu_216_hash_table_accumulator_accumulated_values_d1;
wire    grp_decode_can_message_Pipeline_VITIS_LOOP_182_4_fu_229_ap_start;
wire    grp_decode_can_message_Pipeline_VITIS_LOOP_182_4_fu_229_ap_done;
wire    grp_decode_can_message_Pipeline_VITIS_LOOP_182_4_fu_229_ap_idle;
wire    grp_decode_can_message_Pipeline_VITIS_LOOP_182_4_fu_229_ap_ready;
wire   [15:0] grp_decode_can_message_Pipeline_VITIS_LOOP_182_4_fu_229_hash_table_accumulator_accumulated_values_address0;
wire    grp_decode_can_message_Pipeline_VITIS_LOOP_182_4_fu_229_hash_table_accumulator_accumulated_values_ce0;
wire    grp_decode_can_message_Pipeline_VITIS_LOOP_182_4_fu_229_hash_table_accumulator_accumulated_values_we0;
wire   [63:0] grp_decode_can_message_Pipeline_VITIS_LOOP_182_4_fu_229_hash_table_accumulator_accumulated_values_d0;
wire   [15:0] grp_decode_can_message_Pipeline_VITIS_LOOP_182_4_fu_229_hash_table_accumulator_accumulated_values_address1;
wire    grp_decode_can_message_Pipeline_VITIS_LOOP_182_4_fu_229_hash_table_accumulator_accumulated_values_ce1;
wire   [8:0] grp_decode_can_message_Pipeline_VITIS_LOOP_182_4_fu_229_signal_def_mem_address0;
wire    grp_decode_can_message_Pipeline_VITIS_LOOP_182_4_fu_229_signal_def_mem_ce0;
wire   [6:0] grp_decode_can_message_Pipeline_VITIS_LOOP_182_4_fu_229_decoded_signals_address0;
wire    grp_decode_can_message_Pipeline_VITIS_LOOP_182_4_fu_229_decoded_signals_ce0;
wire    grp_decode_can_message_Pipeline_VITIS_LOOP_182_4_fu_229_decoded_signals_we0;
wire   [42:0] grp_decode_can_message_Pipeline_VITIS_LOOP_182_4_fu_229_decoded_signals_d0;
reg    grp_decode_can_message_Pipeline_VITIS_LOOP_84_1_fu_205_ap_start_reg;
wire    ap_CS_fsm_state2;
reg   [15:0] mul_ln164_loc_fu_110;
reg   [0:0] icmp_ln84_loc_fu_106;
reg    grp_decode_can_message_Pipeline_VITIS_LOOP_117_2_fu_216_ap_start_reg;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state7;
reg    grp_decode_can_message_Pipeline_VITIS_LOOP_182_4_fu_229_ap_start_reg;
wire    ap_CS_fsm_state12;
wire   [63:0] zext_ln76_fu_309_p1;
wire   [63:0] zext_ln99_fu_320_p1;
wire   [0:0] icmp_ln172_fu_339_p2;
wire   [63:0] zext_ln177_fu_392_p1;
reg   [9:0] i_fu_118;
reg    ap_block_state12_on_subcall_done;
wire   [31:0] add_ln182_fu_417_p2;
wire   [0:0] icmp_ln182_fu_411_p2;
reg    hash_table_lut_index_ce0_local;
reg   [8:0] hash_table_lut_index_address0_local;
reg    hash_table_accumulator_counter_ce0_local;
reg   [8:0] hash_table_accumulator_counter_address0_local;
reg    hash_table_accumulator_counter_we0_local;
reg   [31:0] hash_table_accumulator_counter_d0_local;
wire   [31:0] add_ln110_fu_325_p2;
reg    msg_lut_ce0_local;
reg   [8:0] msg_lut_address0_local;
wire   [3:0] trunc_ln13_1_fu_271_p1;
wire   [8:0] p_shl1_fu_275_p3;
wire   [8:0] trunc_ln13_fu_267_p1;
wire   [11:0] tmp_fu_369_p3;
wire   [15:0] p_shl_fu_362_p3;
wire   [15:0] zext_ln184_fu_376_p1;
wire   [31:0] conv_i_i73_fu_407_p1;
reg   [11:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
reg    ap_ST_fsm_state12_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 12'd1;
#0 grp_decode_can_message_Pipeline_VITIS_LOOP_84_1_fu_205_ap_start_reg = 1'b0;
#0 grp_decode_can_message_Pipeline_VITIS_LOOP_117_2_fu_216_ap_start_reg = 1'b0;
#0 grp_decode_can_message_Pipeline_VITIS_LOOP_182_4_fu_229_ap_start_reg = 1'b0;
#0 i_fu_118 = 10'd0;
end

decode_can_message_decode_can_message_Pipeline_VITIS_LOOP_84_1 grp_decode_can_message_Pipeline_VITIS_LOOP_84_1_fu_205(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_decode_can_message_Pipeline_VITIS_LOOP_84_1_fu_205_ap_start),
    .ap_done(grp_decode_can_message_Pipeline_VITIS_LOOP_84_1_fu_205_ap_done),
    .ap_idle(grp_decode_can_message_Pipeline_VITIS_LOOP_84_1_fu_205_ap_idle),
    .ap_ready(grp_decode_can_message_Pipeline_VITIS_LOOP_84_1_fu_205_ap_ready),
    .zext_ln84(hash_index_reg_450),
    .hash_table_message_id_address0(grp_decode_can_message_Pipeline_VITIS_LOOP_84_1_fu_205_hash_table_message_id_address0),
    .hash_table_message_id_ce0(grp_decode_can_message_Pipeline_VITIS_LOOP_84_1_fu_205_hash_table_message_id_ce0),
    .hash_table_message_id_q0(hash_table_message_id_q0),
    .empty(message_id_reg_445),
    .hash_index_1_out(grp_decode_can_message_Pipeline_VITIS_LOOP_84_1_fu_205_hash_index_1_out),
    .hash_index_1_out_ap_vld(grp_decode_can_message_Pipeline_VITIS_LOOP_84_1_fu_205_hash_index_1_out_ap_vld),
    .mul_ln164_out(grp_decode_can_message_Pipeline_VITIS_LOOP_84_1_fu_205_mul_ln164_out),
    .mul_ln164_out_ap_vld(grp_decode_can_message_Pipeline_VITIS_LOOP_84_1_fu_205_mul_ln164_out_ap_vld),
    .icmp_ln84_out(grp_decode_can_message_Pipeline_VITIS_LOOP_84_1_fu_205_icmp_ln84_out),
    .icmp_ln84_out_ap_vld(grp_decode_can_message_Pipeline_VITIS_LOOP_84_1_fu_205_icmp_ln84_out_ap_vld)
);

decode_can_message_decode_can_message_Pipeline_VITIS_LOOP_117_2 grp_decode_can_message_Pipeline_VITIS_LOOP_117_2_fu_216(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_decode_can_message_Pipeline_VITIS_LOOP_117_2_fu_216_ap_start),
    .ap_done(grp_decode_can_message_Pipeline_VITIS_LOOP_117_2_fu_216_ap_done),
    .ap_idle(grp_decode_can_message_Pipeline_VITIS_LOOP_117_2_fu_216_ap_idle),
    .ap_ready(grp_decode_can_message_Pipeline_VITIS_LOOP_117_2_fu_216_ap_ready),
    .num_signals3(reg_255),
    .empty(trunc_ln117_reg_489),
    .signal_def_mem_address0(grp_decode_can_message_Pipeline_VITIS_LOOP_117_2_fu_216_signal_def_mem_address0),
    .signal_def_mem_ce0(grp_decode_can_message_Pipeline_VITIS_LOOP_117_2_fu_216_signal_def_mem_ce0),
    .signal_def_mem_q0(signal_def_mem_q0),
    .signal_def_mem_address1(grp_decode_can_message_Pipeline_VITIS_LOOP_117_2_fu_216_signal_def_mem_address1),
    .signal_def_mem_ce1(grp_decode_can_message_Pipeline_VITIS_LOOP_117_2_fu_216_signal_def_mem_ce1),
    .signal_def_mem_q1(signal_def_mem_q1),
    .message_data2(message_data_reg_455),
    .mul_ln164_reload(mul_ln164_loc_fu_110),
    .hash_table_accumulator_accumulated_values_address0(grp_decode_can_message_Pipeline_VITIS_LOOP_117_2_fu_216_hash_table_accumulator_accumulated_values_address0),
    .hash_table_accumulator_accumulated_values_ce0(grp_decode_can_message_Pipeline_VITIS_LOOP_117_2_fu_216_hash_table_accumulator_accumulated_values_ce0),
    .hash_table_accumulator_accumulated_values_we0(grp_decode_can_message_Pipeline_VITIS_LOOP_117_2_fu_216_hash_table_accumulator_accumulated_values_we0),
    .hash_table_accumulator_accumulated_values_d0(grp_decode_can_message_Pipeline_VITIS_LOOP_117_2_fu_216_hash_table_accumulator_accumulated_values_d0),
    .hash_table_accumulator_accumulated_values_q0(hash_table_accumulator_accumulated_values_q0),
    .hash_table_accumulator_accumulated_values_address1(grp_decode_can_message_Pipeline_VITIS_LOOP_117_2_fu_216_hash_table_accumulator_accumulated_values_address1),
    .hash_table_accumulator_accumulated_values_ce1(grp_decode_can_message_Pipeline_VITIS_LOOP_117_2_fu_216_hash_table_accumulator_accumulated_values_ce1),
    .hash_table_accumulator_accumulated_values_we1(grp_decode_can_message_Pipeline_VITIS_LOOP_117_2_fu_216_hash_table_accumulator_accumulated_values_we1),
    .hash_table_accumulator_accumulated_values_d1(grp_decode_can_message_Pipeline_VITIS_LOOP_117_2_fu_216_hash_table_accumulator_accumulated_values_d1),
    .hash_table_accumulator_accumulated_values_q1(hash_table_accumulator_accumulated_values_q1),
    .zext_ln117(reg_255)
);

decode_can_message_decode_can_message_Pipeline_VITIS_LOOP_182_4 grp_decode_can_message_Pipeline_VITIS_LOOP_182_4_fu_229(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_decode_can_message_Pipeline_VITIS_LOOP_182_4_fu_229_ap_start),
    .ap_done(grp_decode_can_message_Pipeline_VITIS_LOOP_182_4_fu_229_ap_done),
    .ap_idle(grp_decode_can_message_Pipeline_VITIS_LOOP_182_4_fu_229_ap_idle),
    .ap_ready(grp_decode_can_message_Pipeline_VITIS_LOOP_182_4_fu_229_ap_ready),
    .empty_27(empty_reg_549),
    .num_signals_150(reg_255),
    .mul_ln184(add_ln184_reg_515),
    .hash_table_accumulator_accumulated_values_address0(grp_decode_can_message_Pipeline_VITIS_LOOP_182_4_fu_229_hash_table_accumulator_accumulated_values_address0),
    .hash_table_accumulator_accumulated_values_ce0(grp_decode_can_message_Pipeline_VITIS_LOOP_182_4_fu_229_hash_table_accumulator_accumulated_values_ce0),
    .hash_table_accumulator_accumulated_values_we0(grp_decode_can_message_Pipeline_VITIS_LOOP_182_4_fu_229_hash_table_accumulator_accumulated_values_we0),
    .hash_table_accumulator_accumulated_values_d0(grp_decode_can_message_Pipeline_VITIS_LOOP_182_4_fu_229_hash_table_accumulator_accumulated_values_d0),
    .hash_table_accumulator_accumulated_values_address1(grp_decode_can_message_Pipeline_VITIS_LOOP_182_4_fu_229_hash_table_accumulator_accumulated_values_address1),
    .hash_table_accumulator_accumulated_values_ce1(grp_decode_can_message_Pipeline_VITIS_LOOP_182_4_fu_229_hash_table_accumulator_accumulated_values_ce1),
    .hash_table_accumulator_accumulated_values_q1(hash_table_accumulator_accumulated_values_q1),
    .empty(trunc_ln182_reg_539),
    .signal_def_mem_address0(grp_decode_can_message_Pipeline_VITIS_LOOP_182_4_fu_229_signal_def_mem_address0),
    .signal_def_mem_ce0(grp_decode_can_message_Pipeline_VITIS_LOOP_182_4_fu_229_signal_def_mem_ce0),
    .signal_def_mem_q0(signal_def_mem_q0),
    .conv_i32(hash_table_accumulator_counter_load_1_reg_520),
    .decoded_signals_address0(grp_decode_can_message_Pipeline_VITIS_LOOP_182_4_fu_229_decoded_signals_address0),
    .decoded_signals_ce0(grp_decode_can_message_Pipeline_VITIS_LOOP_182_4_fu_229_decoded_signals_ce0),
    .decoded_signals_we0(grp_decode_can_message_Pipeline_VITIS_LOOP_182_4_fu_229_decoded_signals_we0),
    .decoded_signals_d0(grp_decode_can_message_Pipeline_VITIS_LOOP_182_4_fu_229_decoded_signals_d0)
);

decode_can_message_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .message(message),
    .num_decoded_signals_o(num_decoded_signals_o),
    .num_decoded_signals_o_ap_vld(num_decoded_signals_o_ap_vld),
    .num_decoded_signals_i(num_decoded_signals_i)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_decode_can_message_Pipeline_VITIS_LOOP_117_2_fu_216_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state6)) begin
            grp_decode_can_message_Pipeline_VITIS_LOOP_117_2_fu_216_ap_start_reg <= 1'b1;
        end else if ((grp_decode_can_message_Pipeline_VITIS_LOOP_117_2_fu_216_ap_ready == 1'b1)) begin
            grp_decode_can_message_Pipeline_VITIS_LOOP_117_2_fu_216_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_decode_can_message_Pipeline_VITIS_LOOP_182_4_fu_229_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state11)) begin
            grp_decode_can_message_Pipeline_VITIS_LOOP_182_4_fu_229_ap_start_reg <= 1'b1;
        end else if ((grp_decode_can_message_Pipeline_VITIS_LOOP_182_4_fu_229_ap_ready == 1'b1)) begin
            grp_decode_can_message_Pipeline_VITIS_LOOP_182_4_fu_229_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_decode_can_message_Pipeline_VITIS_LOOP_84_1_fu_205_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_decode_can_message_Pipeline_VITIS_LOOP_84_1_fu_205_ap_start_reg <= 1'b1;
        end else if ((grp_decode_can_message_Pipeline_VITIS_LOOP_84_1_fu_205_ap_ready == 1'b1)) begin
            grp_decode_can_message_Pipeline_VITIS_LOOP_84_1_fu_205_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln84_loc_load_load_fu_306_p1 == 1'd0))) begin
        i_fu_118 <= 10'd0;
    end else if (((1'b0 == ap_block_state12_on_subcall_done) & (1'b1 == ap_CS_fsm_state12))) begin
        i_fu_118 <= add_ln172_reg_500;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        add_ln172_reg_500 <= add_ln172_fu_345_p2;
        hash_table_accumulator_counter_addr_1_reg_510 <= zext_ln172_fu_351_p1;
        zext_ln172_reg_505[9 : 0] <= zext_ln172_fu_351_p1[9 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        add_ln184_reg_515[15 : 2] <= add_ln184_fu_380_p2[15 : 2];
        hash_table_accumulator_counter_load_1_reg_520 <= hash_table_accumulator_counter_q0;
        icmp_ln174_reg_525 <= icmp_ln174_fu_386_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        empty_reg_549 <= empty_fu_402_p1;
        num_decoded_signals_read_reg_544 <= num_decoded_signals_i;
        trunc_ln182_reg_539 <= trunc_ln182_fu_397_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        hash_index_reg_450 <= hash_index_fu_283_p2;
        message_data_reg_455 <= {{message[127:64]}};
        message_id_reg_445 <= message_id_fu_262_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        hash_table_accumulator_counter_addr_reg_472 <= zext_ln76_fu_309_p1;
        icmp_ln84_loc_load_reg_463 <= icmp_ln84_loc_fu_106;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_decode_can_message_Pipeline_VITIS_LOOP_84_1_fu_205_icmp_ln84_out_ap_vld == 1'b1))) begin
        icmp_ln84_loc_fu_106 <= grp_decode_can_message_Pipeline_VITIS_LOOP_84_1_fu_205_icmp_ln84_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_decode_can_message_Pipeline_VITIS_LOOP_84_1_fu_205_mul_ln164_out_ap_vld == 1'b1))) begin
        mul_ln164_loc_fu_110 <= grp_decode_can_message_Pipeline_VITIS_LOOP_84_1_fu_205_mul_ln164_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state11))) begin
        reg_255 <= {{msg_lut_q0[22:16]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        trunc_ln117_reg_489 <= trunc_ln117_fu_332_p1;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state12_on_subcall_done)) begin
        ap_ST_fsm_state12_blk = 1'b1;
    end else begin
        ap_ST_fsm_state12_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_decode_can_message_Pipeline_VITIS_LOOP_84_1_fu_205_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

always @ (*) begin
    if ((grp_decode_can_message_Pipeline_VITIS_LOOP_117_2_fu_216_ap_done == 1'b0)) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) & ((icmp_ln172_fu_339_p2 == 1'd1) | (icmp_ln84_loc_load_reg_463 == 1'd1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) & ((icmp_ln172_fu_339_p2 == 1'd1) | (icmp_ln84_loc_load_reg_463 == 1'd1)))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) & (icmp_ln174_reg_525 == 1'd0))) begin
        hash_table_accumulator_accumulated_values_address0 = grp_decode_can_message_Pipeline_VITIS_LOOP_182_4_fu_229_hash_table_accumulator_accumulated_values_address0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        hash_table_accumulator_accumulated_values_address0 = grp_decode_can_message_Pipeline_VITIS_LOOP_117_2_fu_216_hash_table_accumulator_accumulated_values_address0;
    end else begin
        hash_table_accumulator_accumulated_values_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) & (icmp_ln174_reg_525 == 1'd0))) begin
        hash_table_accumulator_accumulated_values_address1 = grp_decode_can_message_Pipeline_VITIS_LOOP_182_4_fu_229_hash_table_accumulator_accumulated_values_address1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        hash_table_accumulator_accumulated_values_address1 = grp_decode_can_message_Pipeline_VITIS_LOOP_117_2_fu_216_hash_table_accumulator_accumulated_values_address1;
    end else begin
        hash_table_accumulator_accumulated_values_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) & (icmp_ln174_reg_525 == 1'd0))) begin
        hash_table_accumulator_accumulated_values_ce0 = grp_decode_can_message_Pipeline_VITIS_LOOP_182_4_fu_229_hash_table_accumulator_accumulated_values_ce0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        hash_table_accumulator_accumulated_values_ce0 = grp_decode_can_message_Pipeline_VITIS_LOOP_117_2_fu_216_hash_table_accumulator_accumulated_values_ce0;
    end else begin
        hash_table_accumulator_accumulated_values_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) & (icmp_ln174_reg_525 == 1'd0))) begin
        hash_table_accumulator_accumulated_values_ce1 = grp_decode_can_message_Pipeline_VITIS_LOOP_182_4_fu_229_hash_table_accumulator_accumulated_values_ce1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        hash_table_accumulator_accumulated_values_ce1 = grp_decode_can_message_Pipeline_VITIS_LOOP_117_2_fu_216_hash_table_accumulator_accumulated_values_ce1;
    end else begin
        hash_table_accumulator_accumulated_values_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) & (icmp_ln174_reg_525 == 1'd0))) begin
        hash_table_accumulator_accumulated_values_d0 = grp_decode_can_message_Pipeline_VITIS_LOOP_182_4_fu_229_hash_table_accumulator_accumulated_values_d0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        hash_table_accumulator_accumulated_values_d0 = grp_decode_can_message_Pipeline_VITIS_LOOP_117_2_fu_216_hash_table_accumulator_accumulated_values_d0;
    end else begin
        hash_table_accumulator_accumulated_values_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) & (icmp_ln174_reg_525 == 1'd0))) begin
        hash_table_accumulator_accumulated_values_we0 = grp_decode_can_message_Pipeline_VITIS_LOOP_182_4_fu_229_hash_table_accumulator_accumulated_values_we0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        hash_table_accumulator_accumulated_values_we0 = grp_decode_can_message_Pipeline_VITIS_LOOP_117_2_fu_216_hash_table_accumulator_accumulated_values_we0;
    end else begin
        hash_table_accumulator_accumulated_values_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        hash_table_accumulator_accumulated_values_we1 = grp_decode_can_message_Pipeline_VITIS_LOOP_117_2_fu_216_hash_table_accumulator_accumulated_values_we1;
    end else begin
        hash_table_accumulator_accumulated_values_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        hash_table_accumulator_counter_address0_local = hash_table_accumulator_counter_addr_1_reg_510;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        hash_table_accumulator_counter_address0_local = zext_ln172_fu_351_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        hash_table_accumulator_counter_address0_local = hash_table_accumulator_counter_addr_reg_472;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        hash_table_accumulator_counter_address0_local = zext_ln76_fu_309_p1;
    end else begin
        hash_table_accumulator_counter_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | ((1'b0 == ap_block_state12_on_subcall_done) & (1'b1 == ap_CS_fsm_state12)))) begin
        hash_table_accumulator_counter_ce0_local = 1'b1;
    end else begin
        hash_table_accumulator_counter_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        hash_table_accumulator_counter_d0_local = 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        hash_table_accumulator_counter_d0_local = add_ln110_fu_325_p2;
    end else begin
        hash_table_accumulator_counter_d0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | ((1'b0 == ap_block_state12_on_subcall_done) & (1'b1 == ap_CS_fsm_state12) & (icmp_ln174_reg_525 == 1'd0)))) begin
        hash_table_accumulator_counter_we0_local = 1'b1;
    end else begin
        hash_table_accumulator_counter_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        hash_table_lut_index_address0_local = zext_ln172_reg_505;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        hash_table_lut_index_address0_local = zext_ln76_fu_309_p1;
    end else begin
        hash_table_lut_index_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state3))) begin
        hash_table_lut_index_ce0_local = 1'b1;
    end else begin
        hash_table_lut_index_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        msg_lut_address0_local = zext_ln177_fu_392_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        msg_lut_address0_local = zext_ln99_fu_320_p1;
    end else begin
        msg_lut_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state4))) begin
        msg_lut_ce0_local = 1'b1;
    end else begin
        msg_lut_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln182_fu_411_p2 == 1'd0) & (1'b0 == ap_block_state12_on_subcall_done) & (1'b1 == ap_CS_fsm_state12) & (icmp_ln174_reg_525 == 1'd0))) begin
        num_decoded_signals_o = add_ln182_fu_417_p2;
    end else begin
        num_decoded_signals_o = num_decoded_signals_i;
    end
end

always @ (*) begin
    if (((icmp_ln182_fu_411_p2 == 1'd0) & (1'b0 == ap_block_state12_on_subcall_done) & (1'b1 == ap_CS_fsm_state12) & (icmp_ln174_reg_525 == 1'd0))) begin
        num_decoded_signals_o_ap_vld = 1'b1;
    end else begin
        num_decoded_signals_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) & (icmp_ln174_reg_525 == 1'd0))) begin
        signal_def_mem_address0 = grp_decode_can_message_Pipeline_VITIS_LOOP_182_4_fu_229_signal_def_mem_address0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        signal_def_mem_address0 = grp_decode_can_message_Pipeline_VITIS_LOOP_117_2_fu_216_signal_def_mem_address0;
    end else begin
        signal_def_mem_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) & (icmp_ln174_reg_525 == 1'd0))) begin
        signal_def_mem_ce0 = grp_decode_can_message_Pipeline_VITIS_LOOP_182_4_fu_229_signal_def_mem_ce0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        signal_def_mem_ce0 = grp_decode_can_message_Pipeline_VITIS_LOOP_117_2_fu_216_signal_def_mem_ce0;
    end else begin
        signal_def_mem_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        signal_def_mem_ce1 = grp_decode_can_message_Pipeline_VITIS_LOOP_117_2_fu_216_signal_def_mem_ce1;
    end else begin
        signal_def_mem_ce1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (grp_decode_can_message_Pipeline_VITIS_LOOP_84_1_fu_205_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln84_loc_load_load_fu_306_p1 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            if (((1'b1 == ap_CS_fsm_state7) & (grp_decode_can_message_Pipeline_VITIS_LOOP_117_2_fu_216_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            if (((1'b1 == ap_CS_fsm_state8) & ((icmp_ln172_fu_339_p2 == 1'd1) | (icmp_ln84_loc_load_reg_463 == 1'd1)))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state9 : begin
            if (((1'b1 == ap_CS_fsm_state9) & (icmp_ln174_fu_386_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            if (((1'b0 == ap_block_state12_on_subcall_done) & (1'b1 == ap_CS_fsm_state12))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln110_fu_325_p2 = (hash_table_accumulator_counter_q0 + 32'd1);

assign add_ln172_fu_345_p2 = (i_fu_118 + 10'd1);

assign add_ln182_fu_417_p2 = (num_decoded_signals_read_reg_544 + conv_i_i73_fu_407_p1);

assign add_ln184_fu_380_p2 = (p_shl_fu_362_p3 + zext_ln184_fu_376_p1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state12_on_subcall_done = ((grp_decode_can_message_Pipeline_VITIS_LOOP_182_4_fu_229_ap_done == 1'b0) & (icmp_ln174_reg_525 == 1'd0));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign conv_i_i73_fu_407_p1 = reg_255;

assign decoded_signals_address0 = grp_decode_can_message_Pipeline_VITIS_LOOP_182_4_fu_229_decoded_signals_address0;

assign decoded_signals_ce0 = grp_decode_can_message_Pipeline_VITIS_LOOP_182_4_fu_229_decoded_signals_ce0;

assign decoded_signals_d0 = grp_decode_can_message_Pipeline_VITIS_LOOP_182_4_fu_229_decoded_signals_d0;

assign decoded_signals_we0 = grp_decode_can_message_Pipeline_VITIS_LOOP_182_4_fu_229_decoded_signals_we0;

assign empty_fu_402_p1 = num_decoded_signals_i[6:0];

assign grp_decode_can_message_Pipeline_VITIS_LOOP_117_2_fu_216_ap_start = grp_decode_can_message_Pipeline_VITIS_LOOP_117_2_fu_216_ap_start_reg;

assign grp_decode_can_message_Pipeline_VITIS_LOOP_182_4_fu_229_ap_start = grp_decode_can_message_Pipeline_VITIS_LOOP_182_4_fu_229_ap_start_reg;

assign grp_decode_can_message_Pipeline_VITIS_LOOP_84_1_fu_205_ap_start = grp_decode_can_message_Pipeline_VITIS_LOOP_84_1_fu_205_ap_start_reg;

assign hash_index_fu_283_p2 = (p_shl1_fu_275_p3 - trunc_ln13_fu_267_p1);

assign hash_table_accumulator_accumulated_values_d1 = grp_decode_can_message_Pipeline_VITIS_LOOP_117_2_fu_216_hash_table_accumulator_accumulated_values_d1;

assign hash_table_accumulator_counter_address0 = hash_table_accumulator_counter_address0_local;

assign hash_table_accumulator_counter_ce0 = hash_table_accumulator_counter_ce0_local;

assign hash_table_accumulator_counter_d0 = hash_table_accumulator_counter_d0_local;

assign hash_table_accumulator_counter_we0 = hash_table_accumulator_counter_we0_local;

assign hash_table_lut_index_address0 = hash_table_lut_index_address0_local;

assign hash_table_lut_index_ce0 = hash_table_lut_index_ce0_local;

assign hash_table_message_id_address0 = grp_decode_can_message_Pipeline_VITIS_LOOP_84_1_fu_205_hash_table_message_id_address0;

assign hash_table_message_id_ce0 = grp_decode_can_message_Pipeline_VITIS_LOOP_84_1_fu_205_hash_table_message_id_ce0;

assign icmp_ln172_fu_339_p2 = ((i_fu_118 == 10'd512) ? 1'b1 : 1'b0);

assign icmp_ln174_fu_386_p2 = ((hash_table_accumulator_counter_q0 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln182_fu_411_p2 = ((reg_255 == 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln84_loc_load_load_fu_306_p1 = icmp_ln84_loc_fu_106;

assign message_id_fu_262_p1 = message[28:0];

assign msg_lut_address0 = msg_lut_address0_local;

assign msg_lut_ce0 = msg_lut_ce0_local;

assign p_shl1_fu_275_p3 = {{trunc_ln13_1_fu_271_p1}, {5'd0}};

assign p_shl_fu_362_p3 = {{i_fu_118}, {6'd0}};

assign signal_def_mem_address1 = grp_decode_can_message_Pipeline_VITIS_LOOP_117_2_fu_216_signal_def_mem_address1;

assign tmp_fu_369_p3 = {{i_fu_118}, {2'd0}};

assign trunc_ln117_fu_332_p1 = msg_lut_q0[8:0];

assign trunc_ln13_1_fu_271_p1 = message[3:0];

assign trunc_ln13_fu_267_p1 = message[8:0];

assign trunc_ln182_fu_397_p1 = msg_lut_q0[8:0];

assign zext_ln172_fu_351_p1 = i_fu_118;

assign zext_ln177_fu_392_p1 = hash_table_lut_index_q0;

assign zext_ln184_fu_376_p1 = tmp_fu_369_p3;

assign zext_ln76_fu_309_p1 = grp_decode_can_message_Pipeline_VITIS_LOOP_84_1_fu_205_hash_index_1_out;

assign zext_ln99_fu_320_p1 = hash_table_lut_index_q0;

always @ (posedge ap_clk) begin
    zext_ln172_reg_505[63:10] <= 54'b000000000000000000000000000000000000000000000000000000;
    add_ln184_reg_515[1:0] <= 2'b00;
end

endmodule //decode_can_message
